import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { hasEthereum } from '../utils/ethereum'
import { useEffect, useState, useRef } from 'react'
import { ethers } from 'ethers'
import useSwr from 'swr'

const fetcher = (url) => fetch(url).then((res) => res.json())

export default function Home() {

  const [connectedWalletAddress, setConnectedWalletAddressState] = useState('')
  const { data, error } = useSwr('/api/hello', fetcher)

  useEffect( () => {
    if(! hasEthereum()) {
      setConnectedWalletAddressState(`MetaMask unavailable`)
      return
    }
    async function setConnectedWalletAddress() {
      const provider = new ethers.providers.Web3Provider(window.ethereum);
      const signer = provider.getSigner()
      try {
        const signerAddress = await signer.getAddress()
        setConnectedWalletAddressState(`Connected wallet: ${signerAddress}`)
      } catch {
        setConnectedWalletAddressState('No wallet connected')
        return;
      }
    }
    setConnectedWalletAddress();
  }, [])

  if (error) return <div>Failed to load users</div>
  if (!data) return <div>Loading...</div>

  console.log('working')
  console.log(data)

  async function requestAccount() {
    await window.ethereum.request({ method: 'eth_requestAccounts' } )
  }

  function logout () {
    setConnectedWalletAddressState('No wallet connected')
  }

  async function clickTest() {
    console.log('clicked')
    const provider = new ethers.providers.Web3Provider(window.ethereum);
    const signer = provider.getSigner()
    await requestAccount()
    const signerAddress = await signer.getAddress()
    setConnectedWalletAddressState(`Connected wallet: ${signerAddress}`)

  }

  async function claim() {
    const provider = new ethers.providers.Web3Provider(window.ethereum)
    const signer = provider.getSigner()
    const contract = new ethers.Contract('0xa1de2592f04b5829f7e23e18dd35e91d13be8b5c', ['function claim(uint256 id)'], signer)

    const transaction = await contract.claim(5)
    await transaction.wait()

    console.log(transaction)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        {data.name}
      </div>

      <main className={styles.main}>
        <h1 className={styles.title}>
          BSCPad Projects
        </h1>

        <div className={styles.grid}>

          <button onClick={clickTest}>test</button>
          <button onClick={logout}>logout</button>
          <button onClick={claim}>claim</button>

          <div className="h-4">
            { connectedWalletAddress && <p className="text-md">{connectedWalletAddress}</p> }
          </div>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
